name: 'XeLaTeX Action'
description: 'Compile LaTeX documents using XeLaTeX with full TeXLive support'
author: 'Voioo'
branding:
  icon: 'book'
  color: 'blue'

inputs:
  file:
    description: 'LaTeX file(s) to compile'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
